routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
  
Route::get('/dashboard','HomeController@index');

Route::resource('/siswa','SiswaController');

Route::resource('/pegawai','PegawaiController');

Route::resource('/mapel','MapelController');

Route::resource('/jadwal','JadwalController');

Route::resource('/kelas','KelasController');
Route::put('kelas/upload/{id}','KelasController@uploadImage')->name('kelas.upload');
Route::get('/list-kelas','KelasController@getKelas')->name('list.kelas');

Route::resource('/absensi','AbsensiController');
Route::get('/absensi/cetak/{id}', 'AbsensiController@cetak')->name('absensi.cetak');
Route::get('/laporan','AbsensiController@laporan')->name('laporan.index');
Route::get('/laporan/list-kelas','AbsensiController@getKelas')->name('laporan.list.kelas');
Route::get('/absensi/rekap/{id}', 'AbsensiController@cetakRekap')->name('absensi.rekap');

Route::get('siswa/reset/{id}','SiswaController@reset');
Route::get('pegawai/reset/{id}','PegawaiController@reset');

//guru login
Route::get('/daftar/kelas','KelasController@kelasPegawai')->name('kelas.pegawai');
Route::get('/daftar/laporan','AbsensiController@laporanPegawai')->name('laporan.pegawai');


});

app/Absensi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Absensi extends Model
{
    protected $table = 'absensi';

    protected $fillable = ['daftar_kelas_id', 'siswa_id','keterangan'];

     //relasi ke tabel jadwal
     public function siswa()
     {
         return $this->belongsTo('App\Siswa');
     }

     //relasi ke tabel daftar kelas
     public function daftar_kelas()
     {
         return $this->belongsTo('App\Kelas');
     }

     public function getKeteranganFormattedAttribute()
     {
         $value = '';

         if($this->keterangan == 1 ){
             $value = "Hadir";
         }
         if($this->keterangan == 2 ){
             $value = "Izin";
         }
         if($this->keterangan == 3 ){
             $value = "Sakit";
         }
         if($this->keterangan == 4 ){
             $value = "Alpa";
         }

         return $value;
     }

}

app/Jadwal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jadwal extends Model
{
    protected $table = 'jadwal';

    protected $fillable = ['kelas', 'hari', 'waktu_awal','waktu_akhir', 'mapel_id', 'pegawai_id'];

     //relasi ke tabel mapel
     public function mapel()
     {
     	return $this->belongsTo('App\Mapel');
     }

      //relasi ke tabel pegawai
      public function pegawai()
      {
          return $this->belongsTo('App\Pegawai');
      }

      public function daftar_kelas(){
      	return $this->hasMany('App\Kelas','jadwal_id');
      }

      public function getHariFormattedAttribute()
        {
            $value = '';

            if($this->hari == 1 ){
                $value = "Senin";
            }
            if($this->hari == 2 ){
                $value = "Selasa";
            }
            if($this->hari == 3 ){
                $value = "Rabu";
            }
            if($this->hari == 4 ){
                $value = "Kamis";
            }
            if($this->hari == 5){
                $value = "Jumat";
            }

            return $value;
        }

        public function getKelasFormattedAttribute()
        {
            $value = '';

            if($this->kelas == 1 ){
                $value = "X RPL";
            }
            if($this->kelas == 2 ){
                $value = "X TKJ";
            }
            if($this->kelas == 3 ){
                $value = "X MM";
            }
            if($this->kelas == 4 ){
                $value = "XI RPL";
            }
            if($this->kelas == 5 ){
                $value = "XI TKJ";
            }
            if($this->kelas == 6 ){
                $value = "XI MM";
            }
            if($this->kelas == 7 ){
                $value = "XII RPL";
            }
            if($this->kelas == 8 ){
                $value = "XII TKJ";
            }
            if($this->kelas == 9 ){
                $value = "XII MM";
            }
           
            return $value;
        }
    

        public function scopeFilter($query, $request)
        {
            if ($request->has('hari') && $request->hari != null) {
                $query->where('hari', $request->hari);
            }

            if ($request->has('kelas') && $request->kelas != null) {
                $query->where('kelas', $request->kelas);
            }

            if ($request->has('mapel_id') && $request->mapel_id != null) {
                $query->where('mapel_id', $request->mapel_id);
            }

            if ($request->has('pegawai_id') && $request->pegawai_id != null) {
                $query->where('pegawai_id', $request->pegawai_id);
            }

            return $query;
        }

}

app/Http/Controllers/API/AbsensiController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Absensi;
use DB;

class AbsensiController extends Controller
{
    public function show($jadwal) 
    {
        $absen = Absensi::with('daftar_kelas')->where('siswa_id', Auth::user()->siswa->id)
                    ->whereHas('daftar_kelas',function ($query) use ($jadwal){
                        $query->where('jadwal_id', $jadwal);
                    })->get()->last();

        return response()->json([
            'success' => true,
            'message' => 'List of All Data',
            'data' => $absen
        ], 200);

    }

    public function absenSiswa(Request $request, $id) 
    {    
        try {

            DB::beginTransaction();

            $success  = Absensi::where('id', $id)
                         ->update([
                             'keterangan' => $request->keterangan,
                             'status' => '1'
                         ]);
            DB::commit();

            return response()->json([
                'status' => $success,
                'data' => ['keterangan' => $request->keterangan],
                'message' => 'Berhasil Absensi'
            ], 200);

        } catch(\Exception $e) {
            DB::rollBack();

            throw $e;
        }

    }
}

app/Http/Controllers/AbsensiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kelas;
use App\Jadwal;
use App\Absensi;
use App\Mapel;
use App\Pegawai;
use App\Siswa;
use PDF;

class AbsensiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
     
        $data = Absensi::where('daftar_kelas_id',$id)->get();
       
        $kelas = Kelas::findOrFail($id);
        
        return view('absensi.show',compact('data','kelas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
        foreach($request->id as $key => $sw) {
            Absensi::where('id', $sw)
            ->update([
                'daftar_kelas_id' => $id,
                'siswa_id' => $request->siswa_id[$key],
                'keterangan' => $request->keterangan[$key]
            ]);
        }

         //arahkan ke halaman absensi
         return redirect(route('absensi.show', $id))->with(['success' => 'Berhasil simpan data']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function cetak($id)
    {
        $kelas = Kelas::findOrFail($id);
        $data = Absensi::where('daftar_kelas_id',$id)->get();
 
    	$pdf = PDF::loadview('absensi.cetak',compact('data','kelas'));
    	return $pdf->stream();
    }

    //menu laporan
    public function laporan()
    {
       //tampilkan data mapel
       $mapel = Mapel::all();
    
       //tampilkan data pagawai
       $pegawai = Pegawai::all();

       $data = Jadwal::get();
       return view('laporan.index',compact('data','mapel','pegawai'));
    }

    public function getKelas(Request $request)
    {
        $data     = Jadwal::filter($request)->get();
        
        $response   = [
            'status'            => false,
            'message'           => 'Data tidak ditemukan',
            'data'              => null
        ];

        if ($data->isNotEmpty()) {
            $response   = [
                'status'            => true,
                'message'           => 'Data ditemukan',
                'data'              => view('laporan.list_kelas', compact('data'))->render(),
            ];
        }

        return response()->json($response);
    }

    public function cetakRekap($id)
    {
        $jadwal = Jadwal::findOrFail($id);
        $data = Siswa::where('kelas',$jadwal->kelas)->get();
  
        $pdf = PDF::setPaper('legal', 'landscape')
        ->loadview('laporan.cetak',compact('data','jadwal'));
    	return $pdf->stream();
    }


    //menu laporan
    public function laporanPegawai()
    {
        $data = Jadwal::where('pegawai_id', auth()->user()->pegawai->id)->get();
        
        return view('laporan.index',compact('data'));
    }

}

resources/views/absensi/cetak.blade.php
<!DOCTYPE html>
<html>
<head>
<title>Absensi {{$kelas->jadwal->mapel->nama}}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Kehadiran Siswa pada KBM</h4>
		<h6>Kelas {{$kelas->jadwal->kelas_formatted}}</h5>
    </center>
    <table>
        <tr>
            <th>Mapel</th>
            <th style="padding-left:10px">:</th>
            <th style="padding-left:10px">{{$kelas->jadwal->mapel->nama}}</th>
        </tr>
        <tr>
            <th>Kompetensi Dasar</th>
            <th style="padding-left:10px">:</th>
            <th style="padding-left:10px">{{$kelas->kd}}</th>
      
        </tr>
        <tr>
            <th>Materi Pokok</th>
            <th style="padding-left:10px">:</th>
            <th style="padding-left:10px">{{$kelas->materi}}</th>
      
        </tr>
    </table>
  
	<table class='table table-bordered'>
		<thead>
			<tr>
                <th style="width: 10px">#</th>
                <th>NISN / NIS</th>
                <th>Nama</th>
                <th>Keterangan</th>
			</tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
            @foreach ($data as $item)
            <tr>
                <td>{{$loop->iteration}}</td>
                <input type="hidden" name="id[]" value="{{$item->id}}">
                <input type="hidden" name="siswa_id[]" value="{{$item->siswa_id}}">
                <td>{{$item->siswa->nisn}} / {{$item->siswa->nis}}</td>
                <td>{{$item->siswa->nama}}</td>
                <td>{{$item->keterangan_formatted}}</td>
              
              </tr>
         
            @endforeach
		</tbody>
	</table>
 
</body>
</html>

resources/views/absensi/show.blade.php
@extends('layouts.main')
@section('content')

<style>
  .form-group {
    margin-bottom: 0!important;
  }
</style>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          {{-- <h1>Buttons</h1> --}}
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Daftar Siswa</li>
          </ol>
        </div>
      </div>
      
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          {{-- form --}}
          <div class="card card-primary card-outline">
            <div class="card-header">
              <h3 class="card-title">
                Absensi Siswa {{$kelas->jadwal->kelas_formatted}}
              </h3>
            </div>
            
             <!-- /.card-header -->
             <div class="card-body">
               <div class="row mb-2">
                  <div class="col-lg-10">
                      <p>Mata Pelajaran : <code>{{$kelas->jadwal->mapel->nama}}</code></p>
                  </div>
                  <div class="col-lg-2">
                      <div class="card-tools">
                          <div class="input-group input-group-sm" >
                            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
          
                            <div class="input-group-append">
                              <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>      
                          </div>
                        </div>
                  </div>

               </div>

          <form action="{{route('absensi.update',$kelas->id)}}" method="POST" >
              @method('put')
              @csrf
             
              <input type="hidden" name="daftar_kelas_id" value="{{$kelas->id}}">
              
              @include('layouts.flash') 
             
              <table class="table table-bordered">
                <thead>                  
                  <tr>
                    <th style="width: 10px">#</th>
                    <th>NISN / NIS</th>
                    <th>Nama</th>
                    <th>Keterangan</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($data as $item)
                  <tr>
                      <td>{{$loop->iteration}}</td>
                      <input type="hidden" name="id[]" value="{{$item->id}}">
                      <input type="hidden" name="siswa_id[]" value="{{$item->siswa_id}}">
                      <td>{{$item->siswa->nisn}} / {{$item->siswa->nis}}</td>
                      <td>{{$item->siswa->nama}}</td>
                      <td>
                        <div class="form-group">
                          <select class="form-control select2 rounded-0" style="width: 100%;" name="keterangan[]" required>
                            <option value = "1" @if($item->keterangan == 1 ) selected @endif>Hadir</option>
                            <option value = "2" @if($item->keterangan == 2 ) selected @endif>Izin</option>
                            <option value = "3" @if($item->keterangan == 3 ) selected @endif>Sakit</option>
                            <option value = "4" @if($item->keterangan == 4 ) selected @endif>Alpa</option>
                          </select>
                        </div>
                      </td>
                    
                    </tr>
               
                  @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer clearfix text-right">
              <button type="submit" class="btn btn-primary rounded-0">Submit</button>
            </div>
            
          </div>
          </form>
          {{-- /form --}}
        </div>
        <!-- /.col -->
      </div>
      <!-- ./row -->

    
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>



@endsection