routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
  
Route::get('/dashboard','HomeController@index');

Route::resource('/siswa','SiswaController');

Route::resource('/pegawai','PegawaiController');

Route::resource('/mapel','MapelController');

Route::resource('/jadwal','JadwalController');

Route::resource('/kelas','KelasController');
Route::put('kelas/upload/{id}','KelasController@uploadImage')->name('kelas.upload');
Route::get('/list-kelas','KelasController@getKelas')->name('list.kelas');

Route::resource('/absensi','AbsensiController');
Route::get('/absensi/cetak/{id}', 'AbsensiController@cetak')->name('absensi.cetak');
Route::get('/laporan','AbsensiController@laporan')->name('laporan.index');
Route::get('/laporan/list-kelas','AbsensiController@getKelas')->name('laporan.list.kelas');
Route::get('/absensi/rekap/{id}', 'AbsensiController@cetakRekap')->name('absensi.rekap');

Route::get('siswa/reset/{id}','SiswaController@reset');
Route::get('pegawai/reset/{id}','PegawaiController@reset');

//guru login
Route::get('/daftar/kelas','KelasController@kelasPegawai')->name('kelas.pegawai');
Route::get('/daftar/laporan','AbsensiController@laporanPegawai')->name('laporan.pegawai');


});

app/Absensi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Absensi extends Model
{
    protected $table = 'absensi';

    protected $fillable = ['daftar_kelas_id', 'siswa_id','keterangan'];

     //relasi ke tabel jadwal
     public function siswa()
     {
         return $this->belongsTo('App\Siswa');
     }

     //relasi ke tabel daftar kelas
     public function daftar_kelas()
     {
         return $this->belongsTo('App\Kelas');
     }

     public function getKeteranganFormattedAttribute()
     {
         $value = '';

         if($this->keterangan == 1 ){
             $value = "Hadir";
         }
         if($this->keterangan == 2 ){
             $value = "Izin";
         }
         if($this->keterangan == 3 ){
             $value = "Sakit";
         }
         if($this->keterangan == 4 ){
             $value = "Alpa";
         }

         return $value;
     }

}

app/Jadwal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jadwal extends Model
{
    protected $table = 'jadwal';

    protected $fillable = ['kelas', 'hari', 'waktu_awal','waktu_akhir', 'mapel_id', 'pegawai_id'];

     //relasi ke tabel mapel
     public function mapel()
     {
     	return $this->belongsTo('App\Mapel');
     }

      //relasi ke tabel pegawai
      public function pegawai()
      {
          return $this->belongsTo('App\Pegawai');
      }

      public function daftar_kelas(){
      	return $this->hasMany('App\Kelas','jadwal_id');
      }

      public function getHariFormattedAttribute()
        {
            $value = '';

            if($this->hari == 1 ){
                $value = "Senin";
            }
            if($this->hari == 2 ){
                $value = "Selasa";
            }
            if($this->hari == 3 ){
                $value = "Rabu";
            }
            if($this->hari == 4 ){
                $value = "Kamis";
            }
            if($this->hari == 5){
                $value = "Jumat";
            }

            return $value;
        }

        public function getKelasFormattedAttribute()
        {
            $value = '';

            if($this->kelas == 1 ){
                $value = "X RPL";
            }
            if($this->kelas == 2 ){
                $value = "X TKJ";
            }
            if($this->kelas == 3 ){
                $value = "X MM";
            }
            if($this->kelas == 4 ){
                $value = "XI RPL";
            }
            if($this->kelas == 5 ){
                $value = "XI TKJ";
            }
            if($this->kelas == 6 ){
                $value = "XI MM";
            }
            if($this->kelas == 7 ){
                $value = "XII RPL";
            }
            if($this->kelas == 8 ){
                $value = "XII TKJ";
            }
            if($this->kelas == 9 ){
                $value = "XII MM";
            }
           
            return $value;
        }
    

        public function scopeFilter($query, $request)
        {
            if ($request->has('hari') && $request->hari != null) {
                $query->where('hari', $request->hari);
            }

            if ($request->has('kelas') && $request->kelas != null) {
                $query->where('kelas', $request->kelas);
            }

            if ($request->has('mapel_id') && $request->mapel_id != null) {
                $query->where('mapel_id', $request->mapel_id);
            }

            if ($request->has('pegawai_id') && $request->pegawai_id != null) {
                $query->where('pegawai_id', $request->pegawai_id);
            }

            return $query;
        }

}

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $table = 'daftar_kelas';

    protected $fillable = ['tanggal','waktu', 'kd', 'materi', 'foto', 'jadwal_id', 'pegawai_id'];

    //relasi ke tabel jadwal
    public function jadwal()
    {
        return $this->belongsTo('App\Jadwal');
    }

     //relasi ke tabel pegawai
     public function pegawai()
     {
         return $this->belongsTo('App\Pegawai');
     }

     //relasi ke tabel absen
     public function absensi(){
    	return $this->hasMany('App\Absensi','daftar_kelas_id');
    }

    public function getHariFormattedAttribute()
    {
        $value = '';

        $tanggal = date('D',strtotime($this->tanggal));
      
        if($tanggal == 'Mon' ){
            $value = "Senin";
        }
        if($tanggal == 'Tue' ){
            $value = "Selasa";
        }
        if($tanggal == 'Wed' ){
            $value = "Rabu";
        }
        if($tanggal == 'Thu' ){
            $value = "Kamis";
        }
        if($tanggal == 'Fri'){
            $value = "Jumat";
        }
        if($tanggal == 'Sat'){
            $value = "Sabtu";
        }
        if($tanggal == 'Sun'){
            $value = "Minggu";
        }

        return $value;
    }



}

resources/views/laporan/cetak.blade.php
<!DOCTYPE html>
<html>
<head>
<title>Absensi {{$jadwal->mapel->nama}}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Kehadiran Siswa pada KBM</h4>
		<h6>Kelas {{$jadwal->kelas_formatted}}</h5>
    </center>
    <table>
        <tr>
            <th>Mata Pelajaran</th>
            <th style="padding-left:10px">:</th>
            <th style="padding-left:10px">{{$jadwal->mapel->nama}}</th>
        </tr>
        <tr>
            <th>Jumlah Pertemuan</th>
            <th style="padding-left:10px">:</th>
            <th style="padding-left:10px">{{$jadwal->daftar_kelas->count()}}</th>
      
        </tr>
        <tr>
            <th>Guru</th>
            <th style="padding-left:10px">:</th>
            <th style="padding-left:10px">{{$jadwal->pegawai->nama}}</th>
      
        </tr>
    </table>
  
	<table class='table table-bordered mt-2'>
		<thead>
			<tr>
                <th class="text-center" style="width: 10px" rowspan="2">#</th>
                <th class="text-center" rowspan="2">NISN / NIS</th>
                <th class="text-center" rowspan="2">Nama</th>
                <th class="text-center" colspan="{{$jadwal->daftar_kelas->count()}}">Pertemuan ke-</th>
            </tr>
            <tr>
                @foreach ($jadwal->daftar_kelas as $pertemuan)
                <th class="text-center" >{{$loop->iteration}}</th>    
                @endforeach
            </tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
            @foreach ($data as $item)
            <tr>
                <td>{{$loop->iteration}}</td>
                <td>{{$item->nisn}} / {{$item->nis}}</td>
                <td>{{$item->nama}}</td>
                @foreach ($jadwal->daftar_kelas as $pertemuan)
                    @foreach ($item->absensi->where('daftar_kelas_id', $pertemuan->id) as $absen)
                        <td>{{$absen->keterangan_formatted}}</td>
                    @endforeach
                @endforeach
                
            </tr>
         
            @endforeach
		</tbody>
	</table>
 
</body>
</html>

resources/views/laporan/index.blade.php
@extends('layouts.main')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                {{-- <h1>Widgets</h1> --}}
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Laporan</li>
                </ol>
              </div>
            </div>
            @if(auth()->user()->pegawai->level == 1)
            <div class="row">
                <div class="col-12">
                  <div class="callout callout-info">
                    {{-- <h5><i class="fas fa-search"></i> Cari :</h5> --}}

                    <div class="row">
                      <div class="col-lg-3">
                          <div class="form-group">
                              <label for="hari">Hari</label>
                              <select id="hari" name="hari" class="form-control select2 rounded-0" style="width: 100%;" required>
                                  <option value = "">-- pilih --</option>
                                  <option value = "1">Senin</option>
                                  <option value = "2">Selasa</option>
                                  <option value = "3">Rabu</option>
                                  <option value = "4">Kamis</option>
                                  <option value = "5">Jumat</option>
                                </select>
                            </div>  
                      </div>
                      <div class="col-lg-3">
                          <div class="form-group">
                              <label for="kelas">Kelas</label>
                              <select id="kelas" name="kelas" class="form-control select2 rounded-0" style="width: 100%;" required>
                                <option value = "">-- pilih --</option>
                                <option value = "1">X RPL</option>
                                <option value = "2">X TKJ</option>
                                <option value = "3">X MM</option>
                                <option value = "4">XI RPL</option>
                                <option value = "5">XI TKJ</option>
                                <option value = "6">XI MM</option>
                                <option value = "7">XII RPL</option>
                                <option value = "8">XII TKJ</option>
                                <option value = "9">XII MM</option>
                              </select>
                            </div>  
                      </div>
                      <div class="col-lg-3">
                          <div class="form-group">
                              <label for="mapel_id">Mata Pelajaran</label>
                              <select id="mapel_id" name="mapel_id" class="form-control select2 rounded-0" style="width: 100%;" required>
                                <option value="">-- pilih --</option>
                                @foreach ($mapel as $m)
                                  <option value="{{$m->id}}"> {{ $m->nama }}</option>
                                @endforeach
                              </select>
                            </div>  
                      </div>
                      <div class="col-lg-3">
                          <div class="form-group">
                              <label for="pegawai_id">Guru</label>
                              <select id="pegawai_id" name="pegawai_id" class="form-control select2 rounded-0" style="width: 100%;" required>
                                <option value="">-- pilih --</option>
                                  @foreach ($pegawai as $p)
                                      <option value="{{$p->id}}"> {{ $p->nama }}</option>
                                  @endforeach
                              </select>
                            </div>  
                      </div>
                    </div>
                    {{-- This page has been enhanced for printing. Click the print button at the bottom of the invoice to test. --}}
                    <div class="text-right">
                      <button type="button" id="btn-cari-laporan" class="btn btn-primary rounded-0"><i class="fas fa-search"></i> Cari</button>
                    </div>
                  </div>
                </div><!-- /.col -->
              </div>
          </div><!-- /.container-fluid -->
            @endif
        </section>
    
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <h5 class="mt-2 mb-2">Daftar Kelas</h5>
            <div class="row" id="list-kelas">
              @include('laporan.list_kelas')             
            </div>
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    
        <a id="back-to-top" href="#" class="btn btn-primary back-to-top" role="button" aria-label="Scroll to top">
          <i class="fas fa-chevron-up"></i>
        </a>
      </div>
      <!-- /.content-wrapper -->
    
@endsection

resources/views/laporan/list_kelas.blade.php
@foreach ($data as $item)
<div class="col-md-3 col-sm-6 col-12">
    <a href="{{route('absensi.rekap',$item->id)}}" target="_blank">
    <div class="info-box bg-info">
    <span class="info-box-icon"><i class="far fa-bookmark"></i></span>
    <div class="info-box-content">
        @if(strlen($item->mapel->nama) > 20)
        <span class="info-box-text">{{substr($item->mapel->nama,0,20)}} ...</span>
        @else
        <span class="info-box-text">{{$item->mapel->nama}}</span>
        @endif
        <span class="info-box-text">{{$item->pegawai->nama}}</span>
        <span class="info-box-number">{{$item->kelas_formatted}} / {{$item->hari_formatted}}</span>
        <div class="progress">
        <div class="progress-bar" style="width: 70%"></div>
        </div>
        <span class="progress-description">
            Jumlah pertemuan {{$item->daftar_kelas->count()}}
        </span>
    </div>
    <!-- /.info-box-content -->
    </div>
    </a>
    <!-- /.info-box -->
</div>
<!-- /.col -->     
@endforeach