routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
  
Route::get('/dashboard','HomeController@index');

Route::resource('/siswa','SiswaController');

Route::resource('/pegawai','PegawaiController');

Route::resource('/mapel','MapelController');

Route::resource('/jadwal','JadwalController');

Route::resource('/kelas','KelasController');
Route::put('kelas/upload/{id}','KelasController@uploadImage')->name('kelas.upload');
Route::get('/list-kelas','KelasController@getKelas')->name('list.kelas');

Route::resource('/absensi','AbsensiController');
Route::get('/absensi/cetak/{id}', 'AbsensiController@cetak')->name('absensi.cetak');
Route::get('/laporan','AbsensiController@laporan')->name('laporan.index');
Route::get('/laporan/list-kelas','AbsensiController@getKelas')->name('laporan.list.kelas');
Route::get('/absensi/rekap/{id}', 'AbsensiController@cetakRekap')->name('absensi.rekap');

Route::get('siswa/reset/{id}','SiswaController@reset');
Route::get('pegawai/reset/{id}','PegawaiController@reset');

//guru login
Route::get('/daftar/kelas','KelasController@kelasPegawai')->name('kelas.pegawai');
Route::get('/daftar/laporan','AbsensiController@laporanPegawai')->name('laporan.pegawai');


});

app/Jadwal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jadwal extends Model
{
    protected $table = 'jadwal';

    protected $fillable = ['kelas', 'hari', 'waktu_awal','waktu_akhir', 'mapel_id', 'pegawai_id'];

     //relasi ke tabel mapel
     public function mapel()
     {
     	return $this->belongsTo('App\Mapel');
     }

      //relasi ke tabel pegawai
      public function pegawai()
      {
          return $this->belongsTo('App\Pegawai');
      }

      public function daftar_kelas(){
      	return $this->hasMany('App\Kelas','jadwal_id');
      }

      public function getHariFormattedAttribute()
        {
            $value = '';

            if($this->hari == 1 ){
                $value = "Senin";
            }
            if($this->hari == 2 ){
                $value = "Selasa";
            }
            if($this->hari == 3 ){
                $value = "Rabu";
            }
            if($this->hari == 4 ){
                $value = "Kamis";
            }
            if($this->hari == 5){
                $value = "Jumat";
            }

            return $value;
        }

        public function getKelasFormattedAttribute()
        {
            $value = '';

            if($this->kelas == 1 ){
                $value = "X RPL";
            }
            if($this->kelas == 2 ){
                $value = "X TKJ";
            }
            if($this->kelas == 3 ){
                $value = "X MM";
            }
            if($this->kelas == 4 ){
                $value = "XI RPL";
            }
            if($this->kelas == 5 ){
                $value = "XI TKJ";
            }
            if($this->kelas == 6 ){
                $value = "XI MM";
            }
            if($this->kelas == 7 ){
                $value = "XII RPL";
            }
            if($this->kelas == 8 ){
                $value = "XII TKJ";
            }
            if($this->kelas == 9 ){
                $value = "XII MM";
            }
           
            return $value;
        }
    

        public function scopeFilter($query, $request)
        {
            if ($request->has('hari') && $request->hari != null) {
                $query->where('hari', $request->hari);
            }

            if ($request->has('kelas') && $request->kelas != null) {
                $query->where('kelas', $request->kelas);
            }

            if ($request->has('mapel_id') && $request->mapel_id != null) {
                $query->where('mapel_id', $request->mapel_id);
            }

            if ($request->has('pegawai_id') && $request->pegawai_id != null) {
                $query->where('pegawai_id', $request->pegawai_id);
            }

            return $query;
        }

}

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $table = 'daftar_kelas';

    protected $fillable = ['tanggal','waktu', 'kd', 'materi', 'foto', 'jadwal_id', 'pegawai_id'];

    //relasi ke tabel jadwal
    public function jadwal()
    {
        return $this->belongsTo('App\Jadwal');
    }

     //relasi ke tabel pegawai
     public function pegawai()
     {
         return $this->belongsTo('App\Pegawai');
     }

     //relasi ke tabel absen
     public function absensi(){
    	return $this->hasMany('App\Absensi','daftar_kelas_id');
    }

    public function getHariFormattedAttribute()
    {
        $value = '';

        $tanggal = date('D',strtotime($this->tanggal));
      
        if($tanggal == 'Mon' ){
            $value = "Senin";
        }
        if($tanggal == 'Tue' ){
            $value = "Selasa";
        }
        if($tanggal == 'Wed' ){
            $value = "Rabu";
        }
        if($tanggal == 'Thu' ){
            $value = "Kamis";
        }
        if($tanggal == 'Fri'){
            $value = "Jumat";
        }
        if($tanggal == 'Sat'){
            $value = "Sabtu";
        }
        if($tanggal == 'Sun'){
            $value = "Minggu";
        }

        return $value;
    }



}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Jadwal;
use App\Kelas;
use App\Siswa;
use App\Absensi;
use App\Mapel;
use App\Pegawai;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //tampilkan data mapel
        $mapel = Mapel::all();
    
        //tampilkan data pagawai
        $pegawai = Pegawai::all();

        $data = Jadwal::get();
        return view('kelas.index',compact('data','mapel','pegawai'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $daftar_kelas = Kelas::create([
                            'tanggal' => $request->tanggal,
                            'waktu' =>  \Carbon\Carbon::now('Asia/Makassar'),
                            'kd' => $request->kd,
                            'materi' => $request->materi,
                            'jadwal_id' => $request->jadwal_id,
                            'pegawai_id' => auth()->user()->pegawai->id
                        ]);

        //dapatkan data kelas dari tabel jadwal
        $kelas = Jadwal::findOrFail( $request->jadwal_id)->kelas;
        
        //dapatkan data siswa berdasarkan kelas
        $siswa = Siswa::where('kelas', $kelas)->get();


        foreach($siswa as $sw) {
            Absensi::create([
                'daftar_kelas_id' => $daftar_kelas->id,
                'siswa_id' => $sw->id,
                'keterangan' => '4'
            ]);
        }
       

        //arahkan ke halaman kelas
        return redirect(route('kelas.show', $request->jadwal_id))->with(['success' => 'Berhasil simpan data']);;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $jadwal = Jadwal::findOrFail($id);

        $data = Kelas::where('jadwal_id',$id)->orderBy('id','DESC')->paginate(10);
       
        return view('kelas.show',compact('data','jadwal'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $kelas = Kelas::findOrFail($id);
        $kelas->update([
            'tanggal' => $request->tanggal,
            'waktu' =>  \Carbon\Carbon::now('Asia/Makassar'),
            'kd' => $request->kd,
            'materi' => $request->materi,
            'jadwal_id' => $request->jadwal_id,
            'pegawai_id' => auth()->user()->pegawai->id
       ]);
        
        return redirect(route('kelas.show', $request->jadwal_id))->with(['success' => 'Berhasil ubah data']);
 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $kelas = Kelas::findOrFail($id);
        $kelas->destroy($id);

        //arahkan ke halaman kelas
        return redirect(route('kelas.show', $request->jadwal_id))->with(['success' => 'Berhasil hapus data']);
    }

    public function uploadImage(Request $request, $id)
    {

       $file = $request->file('foto');
       $name = \Carbon\Carbon::now()->format('Y-m-dH:i:s').'-' .$file->getClientOriginalName(). '.' . $file->getClientOriginalExtension();
       $path = $file->storeAs('/public/images', $name);
       $kelas = Kelas::findOrFail($id);
       $kelas->update(['foto' => $name ]);
       return redirect(route('kelas.show', $request->jadwal_id))->with(['success' => 'Berhasil upload bukti mengajar']);
 
    }

    public function kelasPegawai()
    {
        $data = Jadwal::where('pegawai_id', auth()->user()->pegawai->id)->get();
        
        return view('kelas.index',compact('data'));
    }

    
    
}

resources/views/kelas/edit.blade.php
    <div class="modal fade" id="modal-lg-{{$item->id}}">
        <div class="modal-dialog modal-lg">
        <form role="form" id="quickForm" method="POST" action="{{ "/kelas/$item->id" }}">
            @method('put')
            @csrf
                
          <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Pertemuan ke-{{$loop->iteration}}</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="row">
                        <div class="col-md-6">
                            <label>Tanggal</label>
                            <div class="form-group">
                                  <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                      <input type="date" name="tanggal" class="form-control datetimepicker-input rounded-0" data-target="#reservationdate" value="{{$item->tanggal}}">
                                      <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                          <div class="input-group-text rounded-0"><i class="fa fa-calendar"></i></div>
                                      </div>
                                  </div>
                            </div>
                            <!-- /.form-group -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>Jadwal</label>
                            <input type="hidden" name="jadwal_id" value="{{$jadwal->id}}">
                            <input type="text" class="form-control rounded-0" id="exampleInputEmail1" placeholder="Enter email" value="{{$jadwal->hari_formatted}} / {{$jadwal->waktu_awal}} - {{$jadwal->waktu_akhir}} ">
                          </div>
                          <!-- /.form-group -->
                        </div>
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Kompetensi Dasar</label>
                                <textarea name="kd" class="form-control rounded-0" rows="3" placeholder="Enter ...">{{$item->kd}}</textarea>
                            </div>
                            <!-- /.form-group -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Materi Pokok</label>
                                <textarea name="materi" class="form-control rounded-0" rows="3" placeholder="Enter ...">{{$item->materi}}</textarea>
                            </div>
                            <!-- /.form-group -->
                        </div>
                    </div>
                    <!-- /.row -->
                  
            </div>
            <div class="modal-footer justify-content-right">
              <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </div>
          <!-- /.modal-content -->
        </form>
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
    

resources/views/kelas/list_kelas.blade.php
@foreach ($data as $item)
<div class="col-md-3 col-sm-6 col-12">
    <a href="{{route('kelas.show',$item->id)}}">
    <div class="info-box bg-info">
    <span class="info-box-icon"><i class="far fa-bookmark"></i></span>
    <div class="info-box-content">
        @if(strlen($item->mapel->nama) > 20)
        <span class="info-box-text">{{substr($item->mapel->nama,0,20)}} ...</span>
        @else
        <span class="info-box-text">{{$item->mapel->nama}}</span>
        @endif
        <span class="info-box-text">{{$item->pegawai->nama}}</span>
        <span class="info-box-number">{{$item->kelas_formatted}} / {{$item->hari_formatted}}</span>
        <div class="progress">
        <div class="progress-bar" style="width: 70%"></div>
        </div>
        <span class="progress-description">
            Jumlah pertemuan {{$item->daftar_kelas->count()}}
        </span>
    </div>
    <!-- /.info-box-content -->
    </div>
    </a>
    <!-- /.info-box -->
</div>
<!-- /.col -->     
@endforeach

resources/views/kelas/show.blade.php
@extends('layouts.main')
@section('content')

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          {{-- <h1>Buttons</h1> --}}
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Daftar Jadwal</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
        
          <form action="{{route('kelas.store')}}" method="POST">
            @csrf
            <div class="card card-default">
                <div class="card-header">
                <h3 class="card-title">Buka Kelas {{$jadwal->mapel->nama}} / <strong>{{$jadwal->kelas_formatted}}</strong></h3>
      
                  <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                  </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-6">
                        <label>Tanggal</label>
                        <div class="form-group">
                              <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                  <input type="date" name="tanggal" class="form-control datetimepicker-input rounded-0" data-target="#reservationdate">
                                  <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                      <div class="input-group-text rounded-0"><i class="fa fa-calendar"></i></div>
                                  </div>
                              </div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                      <div class="form-group">
                        <label>Jadwal</label>
                        <input type="hidden" name="jadwal_id" value="{{$jadwal->id}}">
                        <input type="text" class="form-control rounded-0" id="exampleInputEmail1" placeholder="Enter email" value="{{$jadwal->hari_formatted}} / {{$jadwal->waktu_awal}} - {{$jadwal->waktu_akhir}} ">
                      </div>
                      <!-- /.form-group -->
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Kompetensi Dasar</label>
                            <textarea name="kd" class="form-control rounded-0" rows="3" placeholder="Enter ..."></textarea>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Materi Pokok</label>
                            <textarea name="materi" class="form-control rounded-0" rows="3" placeholder="Enter ..."></textarea>
                        </div>
                        <!-- /.form-group -->
                    </div>
                </div>
                <!-- /.row -->
      
            
                </div>
                <!-- /.card-body -->
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-primary rounded-0 .tombol-simpan">Buka Kelas</button>
                </div>
              </div>
            </form>
              <!-- /.card -->
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-header">
              <h3 class="card-title">
                <b>Hallo</b> {{$jadwal->pegawai->nama}}
              </h3>
            </div>


             <!-- /.card-header -->
             <div class="card-body">
               <div class="row">
                  <div class="col-lg-10">
                      <p>Daftar <code>Pertemuan</code></p>
                  </div>
                  <div class="col-lg-2">
                      <div class="card-tools">
                          <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
          
                            <div class="input-group-append">
                              <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                            </div>      
                          </div>
                        </div>
                  </div>

               </div>
  
              @include('layouts.flash') 
              <table class="table table-bordered">
                <thead>                  
                  <tr>
                    <th style="width: 10px">#</th>
                    <th>Tanggal / Buka Kelas</th>
                    <th>Kelas</th>
                    <th>Kompetensi Dasar</th>
                    <th>Materi Pokok</th>
                    <th>Bukti</th>
                    <th>Absensi</th>
                    <th style="width: 60px"></th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($data as $item)
                  <tr>
                      <td>{{$loop->iteration}}</td>
                      <td>{{$item->hari_formatted}}, {{date('d M y',strtotime($item->tanggal)) }} / {{$item->waktu}}</td>
                      <td>{{$item->jadwal->kelas_formatted}}</td>
                      <td>{{$item->kd}}</td>
                      <td>{{$item->materi}}</td>
                      <td><a href="#" data-toggle="modal" data-target="#modal-lg-upload-{{$item->id}}" class="btn btn-block btn-warning btn-sm btn-flat text-white"><i class="fas fa-upload"></i></a></td>
                      <td>
                        <div class="row">
                          <div class="col-lg-6">
                              <a href="{{route('absensi.cetak',$item->id)}}" target="_blank"  class="btn btn-block btn-success btn-sm btn-flat text-white"><i class="fas fa-print"></i></a>
                          </div>
                          <div class="col-lg-6">
                              <a href="{{route('absensi.show',$item->id)}}" class="btn btn-block btn-info btn-sm btn-flat text-white"><i class="fas fa-list"></i></a>
                          </div>
                        </div>
                      </td>
                      <td>
                          <div class="btn-group">
                              <button type="button" class="btn btn-danger btn-sm btn-flat">Action</button>
                              <button type="button" class="btn btn-danger btn-sm btn-flat dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                              </button>
                                {{-- <div class="dropdown-menu" role="menu" style="">
                                  <a class="dropdown-item" href="#">Edit</a>
                                  <a class="dropdown-item" href="#">Delete</a>
                                </div> --}}
                             
                              <div class="dropdown-menu" role="menu" style="">
                                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modal-lg-{{$item->id}}">Edit</a>
                                  <form action={{"/kelas/$item->id"}} method="POST" class="d-inline">
                                    @method('delete')
                                    @csrf
                                      <input type="hidden" name="jadwal_id" value="{{$jadwal->id}}">
                                      <button type="submit" class="dropdown-item" onclick="return confirm('Yakin?')">Hapus</button>
                                  </form>
                                </div>
                            </div>
                      </td>
                    </tr>  
                    @include('kelas.edit', [$item])
                    @include('kelas.upload', [$item])
              
                  @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer clearfix">
              <ul class="pagination pagination-sm m-0 float-right">
                  {{ $data->links() }}
              </ul>
            </div>
            
          </div>
        </div>
        <!-- /.col -->
      </div>
      <!-- ./row -->

    
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>


@endsection

resources/views/kelas/upload.blade.php
    <div class="modal fade" id="modal-lg-upload-{{$item->id}}">
        <div class="modal-dialog modal-lg">
        <form role="form" id="quickForm" method="POST" action="{{ route('kelas.upload',$item->id) }}" enctype="multipart/form-data">
            @method('put')
            @csrf
                
          <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Pertemuan ke-{{$loop->iteration}}</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="row">
                        <div class="col-md-6">
                            <label>Tanggal</label>
                            <div class="form-group">
                                  <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                      <input type="date" name="tanggal" class="form-control datetimepicker-input rounded-0" data-target="#reservationdate" value="{{$item->tanggal}}" readonly>
                                      <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                          <div class="input-group-text rounded-0"><i class="fa fa-calendar"></i></div>
                                      </div>
                                  </div>
                            </div>
                            <!-- /.form-group -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>Jadwal</label>
                            <input type="hidden" name="jadwal_id" value="{{$jadwal->id}}">
                            <input type="text" class="form-control rounded-0" id="exampleInputEmail1" placeholder="Enter email" value="{{$jadwal->hari_formatted}} / {{$jadwal->waktu_awal}} - {{$jadwal->waktu_akhir}} ">
                          </div>
                          <!-- /.form-group -->
                        </div>
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <div class="col-md-6">
                            <label>Bukti Mengajar</label>
                            <div class="form-group">
                                  <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                      <input type="file" name="foto" class="form-control datetimepicker-input rounded-0" data-target="#reservationdate" value="{{$item->tanggal}}">
                                      <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                          <div class="input-group-text rounded-0"><i class="fa fa-upload"></i></div>
                                      </div>
                                  </div>
                            </div>
                            <!-- /.form-group -->
                        </div>
                        <!-- /.col -->
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>Foto</label>
                            <div class="form-group text-center">
                                <img src="{{asset('storage/images/'.$item->foto)}}" alt="" style="max-width:150px;" alt="">
                            </div>
                           </div>
                          <!-- /.form-group -->
                        </div>
                    </div>
                    <!-- /.row -->
                  
            </div>
            <div class="modal-footer justify-content-right">
              <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </div>
          <!-- /.modal-content -->
        </form>
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
    