routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
  
Route::get('/dashboard','HomeController@index');

Route::resource('/siswa','SiswaController');

Route::resource('/pegawai','PegawaiController');

Route::resource('/mapel','MapelController');

Route::resource('/jadwal','JadwalController');

Route::resource('/kelas','KelasController');
Route::put('kelas/upload/{id}','KelasController@uploadImage')->name('kelas.upload');
Route::get('/list-kelas','KelasController@getKelas')->name('list.kelas');

Route::resource('/absensi','AbsensiController');
Route::get('/absensi/cetak/{id}', 'AbsensiController@cetak')->name('absensi.cetak');
Route::get('/laporan','AbsensiController@laporan')->name('laporan.index');
Route::get('/laporan/list-kelas','AbsensiController@getKelas')->name('laporan.list.kelas');
Route::get('/absensi/rekap/{id}', 'AbsensiController@cetakRekap')->name('absensi.rekap');

Route::get('siswa/reset/{id}','SiswaController@reset');
Route::get('pegawai/reset/{id}','PegawaiController@reset');

//guru login
Route::get('/daftar/kelas','KelasController@kelasPegawai')->name('kelas.pegawai');
Route::get('/daftar/laporan','AbsensiController@laporanPegawai')->name('laporan.pegawai');


});

resources/views/layouts/flash.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success rounded-0">
  <button type="button" class="close" data-dismiss="alert">×</button> 
  <i class="fas fa-check"></i> &nbsp;<span>{{ $message }}</span>
</div>
@endif

@if ($message = Session::get('error'))
<div class="alert alert-danger rounded-0">
  <button type="button" class="close" data-dismiss="alert">×</button> 
  <i class="fas fa-times"></i> &nbsp;<span>{{ $message }}</span>
</div>
@endif

resources/views/layouts/footer.blade.php
<footer class="main-footer">
  <strong>Copyright &copy; 2020. &nbsp;</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    {{-- <b>Version</b> 3.0.5 --}}
  </div>
</footer>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>SIA | Home</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{asset('assets/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('assets/dist/css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('dashboard')}}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{ route('logout') }}" class="nav-link" 
           onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
            class="fas fa-th-large"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @extends('layouts.sidebar')

  <!-- Content Wrapper. Contains page content -->
    @yield('content')
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  @extends('layouts.footer')
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{{asset('assets/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap -->
<script src="{{asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{asset('assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('assets/dist/js/adminlte.js')}}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{{asset('assets/dist/js/demo.js')}}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{{asset('assets/plugins/jquery-mousewheel/jquery.mousewheel.js')}}"></script>
<script src="{{asset('assets/plugins/raphael/raphael.min.js')}}"></script>
<script src="{{asset('assets/plugins/jquery-mapael/jquery.mapael.min.js')}}"></script>
<script src="{{asset('assets/plugins/jquery-mapael/maps/usa_states.min.js')}}"></script>
<!-- ChartJS -->
<script src="{{asset('assets/plugins/chart.js/Chart.min.js')}}"></script>

<!-- PAGE SCRIPTS -->
<script src="{{asset('assets/dist/js/pages/dashboard2.js')}}"></script>
{{-- Buka Kelas --}}
<script>
  $(document).ready(function() {
    $("#btn-cari").on('click', function(e) {
        console.log('a')
        e.preventDefault();
        $.ajax({
          url: '{{route("list.kelas")}}',
          data: {
            hari: $("#hari").val(),
            kelas: $("#kelas").val(),
            mapel_id: $("#mapel_id").val(),
            pegawai_id: $("#pegawai_id").val(),
          },
          dataType: 'JSON',
          success: function(response) {
            $("#list-kelas").html('');
            if (response.status) {
              $("#list-kelas").html(response.data);
            }else {
              alert(response.message)
            }
          },
          type: 'GET'
        });
      })
  })
</script>
{{-- Laporan --}}
<script>
    $(document).ready(function() {
      $("#btn-cari-laporan").on('click', function(e) {
          console.log('a')
          e.preventDefault();
          $.ajax({
            url: '{{route("laporan.list.kelas")}}',
            data: {
              hari: $("#hari").val(),
              kelas: $("#kelas").val(),
              mapel_id: $("#mapel_id").val(),
              pegawai_id: $("#pegawai_id").val(),
            },
            dataType: 'JSON',
            success: function(response) {
              $("#list-kelas").html('');
              if (response.status) {
                $("#list-kelas").html(response.data);
              }else {
                alert(response.message)
              }
            },
            type: 'GET'
          });
        })
    })
</script>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    {{-- <a href="index3.html" class="brand-link">
      <img src="{{asset('assets/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a> --}}

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('assets/dist/img/logo.jpeg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{auth()->user()->pegawai->nama}}</a>
        </div>
      </div>
   
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item">
            <a href="{{url('dashboard')}}" class="nav-link {{Request::is('dashboard')?'active':''}}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          @if(auth()->user()->pegawai->level == 1)
       
          <li class="nav-item">
              <a href="{{route('siswa.index')}}" class="nav-link {{Request::is('siswa')?'active':''}}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Siswa
              </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="{{route('pegawai.index')}}" class="nav-link {{Request::is('pegawai')?'active':''}}">
              <i class="nav-icon far fa-address-card"></i>
              <p>
                Pegawai
              </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="{{route('mapel.index')}}" class="nav-link {{Request::is('mapel')?'active':''}}">
              <i class="nav-icon fas fa-book-open"></i>
              <p>
                Mata Pelajaran
              </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="{{route('jadwal.index')}}" class="nav-link {{Request::is('jadwal')?'active':''}}">
              <i class="nav-icon far fa-calendar-alt"></i>
              <p>
                Jadwal
              </p>
            </a>
          </li>          
          
          <li class="nav-header">ABSENSI</li>
          <li class="nav-item has-treeview">
              <a href="{{route('kelas.index')}}" class="nav-link {{Request::is('kelas')?'active':''}}">
                <i class="nav-icon fab fa-buromobelexperte"></i>
                <p>
                  Buka Kelas
                </p>
              </a>
          </li>
        
          <li class="nav-item has-treeview">
              <a href="{{route('laporan.index')}}" class="nav-link {{Request::is('laporan')?'active':''}}">
                <i class="nav-icon fas fa-file-medical-alt"></i>
                <p>
                  Laporan
                </p>
              </a>
          </li>
          @endif

          @if(auth()->user()->pegawai->level == 0)
          <li class="nav-header">ABSENSI</li>
          <li class="nav-item has-treeview">
              <a href="{{route('kelas.pegawai')}}" class="nav-link {{Request::is('daftar/kelas')?'active':''}}">
                <i class="nav-icon fab fa-buromobelexperte"></i>
                <p>
                  Buka Kelas
                </p>
              </a>
          </li>
        
          <li class="nav-item has-treeview">
              <a href="{{route('laporan.pegawai')}}" class="nav-link {{Request::is('daftar/laporan')?'active':''}}">
                <i class="nav-icon fas fa-file-medical-alt"></i>
                <p>
                  Laporan
                </p>
              </a>
          </li>
          @endif
          


        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>